ministryofjustice/hmpps-delius-alfresco-shared-terraform

- README.md
- self-signed/ca/main.tf
- self-signed/ca/output.tf
- self-signed/ca/terraform.tfvars
- self-signed/ca/variables.tf
- self-signed/server/main.tf
- self-signed/server/output.tf
- self-signed/server/terraform.tfvars
- self-signed/server/variables.tf
closes #3 
Self signed certs now upload and in Param store
> Added Self signed certs for Alfresco LB

- common/variables.tf
- env_configs/dev.properties
- self-signed/ca/main.tf
- self-signed/ca/variables.tf
- self-signed/server/main.tf
- self-signed/server/variables.tf
- service-alfresco/s3bucket/main.tf
- service-alfresco/s3bucket/output.tf
- service-alfresco/s3bucket/policies/kms-policy.json
- service-alfresco/s3bucket/policies/s3_cloudtrail_policy.json
- service-alfresco/s3bucket/terraform.tfvars
- service-alfresco/s3bucket/variables.tf
- terraform.tfvars
> Alfresco s3 buckets and KMS key created

- service-alfresco/s3bucket/main.tf
- service-alfresco/s3bucket/output.tf
- service-alfresco/s3bucket/policies/kms-policy.json
- service-alfresco/s3bucket/policies/s3_cloudtrail_policy.json
- service-alfresco/s3bucket/terraform.tfvars
- service-alfresco/s3bucket/variables.tf
> Alfresco s3 buckets done

- env_configs/dev.tfvars
- service-alfresco/iam/main.tf
- service-alfresco/iam/output.tf
- service-alfresco/iam/policies/ec2_external_policy.json
- service-alfresco/iam/policies/ec2_internal_policy.json
- service-alfresco/iam/policies/ecs_role_policy.json
- service-alfresco/iam/terraform.tfvars
- service-alfresco/iam/variables.tf
> Internal IAM roles added

- asg/main.tf
- certs/main.tf
- common/main.tf
- ecs-nginx/main.tf
- iam/main.tf
- rds/main.tf
- s3buckets/main.tf
- security-groups/main.tf
Changed terraform source to master branch
> Updated source to master

- common/main.tf
- common/output.tf
- run.sh
- security-groups/main.tf
> Added nat gateway ips

- README.md
- docker-run.py
- run.sh
- utils/args_parser.py
> BCL IPs added and updated docker-run.py to provide branch name argument

- user_data/user_data.sh
> Now runs tomcat service

- common/main.tf
- elasticache-memcached/main.tf
- elasticache-memcached/output.tf
- elasticache-memcached/terraform.tfvars
- elasticache-memcached/variables.tf
- security-groups/main.tf
- security-groups/output.tf
> WIP - DO NOT MERGE

- jenkins_files/docker-run.Jenkinsfile
> added environments to jenkins file

- README.md
- alf_env_configs/delius-test.properties
- alf_env_configs/delius-training-test.properties
- jenkins_files/docker-sync.Jenkinsfile
- jenkins_files/jenkins-sync.sh
- scripts/s3_copy_contents.sh
> Issue 75 add restore docs

- README.md
- alf_env_configs/delius-test.properties
- jenkins_files/docker-sync.Jenkinsfile
- scripts/get_creds.sh
- scripts/s3_copy_contents.sh
> Increased sts token duration

- alf_env_configs/delius-po-test1.properties
- jenkins_files/docker-sync.Jenkinsfile
> adding delius-po-test1.properties file

- alf_env_configs/delius-test.properties
- jenkins_files/docker-elasticsearch-copy.Jenkinsfile
- scripts/s3_copy_elasticsearch.sh
> Added es copy script and pipeline

- alf_env_configs/delius-po-test2.properties
- jenkins_files/docker-sync.Jenkinsfile
> adding potest2 properties file, adding env to jenkins file

- asg/main.tf
- elasticsearch/main.tf
- security-groups/output.tf
> Added bastion sg to Alf instances

- jenkins_files/Alfresco_Terraform_Apply_Integrated_Environment.Jenkinsfile
- jenkins_files/check_infrastructure.Jenkinsfile
- run.sh
Makes Apply job run hands off
Refactors resource name overrides
> Adds Check_infrastructure job

- alf_env_configs/delius-po-test1.properties
> Added dest bucket var

- alf_env_configs/delius-po-test2.properties
- jenkins_files/docker-elasticsearch-copy.Jenkinsfile
> adding po-test2 env for es restore

- asg/main.tf
- bastion/ec2.tf
- bastion/iam.tf
- bastion/main.tf
- bastion/policies/policy.json
- bastion/terraform.tfvars
- bastion/user_data/userdata.sh
- bastion/variables.tf
- common/output.tf
- security-groups/main.tf
- security-groups/output.tf
> Updated asg groups

- jenkins_files/alfresco_restore.JenkinsFile
> Added smoke test after restore

- modules/asg/main.tf
- user_data/user_data.sh
> Issue 119 removed creds from userdata

- es_admin/main.tf
- jenkins_files/alfresco_restore_content_and_databse_only.JenkinsFile
- restore/set-properties.sh
> Added content and database pipeline only

- jenkins_files/Alfresco_Terraform_Apply_Integrated_Environment.Jenkinsfile
> Always apply common and sgs

- modules/asg/main.tf
- modules/security-groups/main.tf
> Added Sharepoint port 7070 to elb and sg

- asg/variables.tf
- modules/elb/create_elb_with_https/README.md
- modules/elb/create_elb_with_https/main.tf
- modules/elb/create_elb_with_https/outputs.tf
- modules/elb/create_elb_with_https/variables.tf
- terraform.tfvars
> Issue 130 use tg common var for prod

- jenkins_files/Alfresco_Terraform_Apply_Integrated_Environment.Jenkinsfile
- jenkins_files/check_infrastructure.Jenkinsfile
> Added efs to pipeline

- jenkins_files/alfresco_restore.JenkinsFile
- restore/docker-compose-alfresco-restore.yml
- scripts/alfresco-asg-manager.sh
- scripts/alfresco-content-restore.sh
- scripts/alfresco-database-restore.sh
Fixes for backups task failing
> Add parallel runs

- jenkins_files/alfresco_backup_content_and_databse_only.JenkinsFile
- jenkins_files/alfresco_restore.JenkinsFile
- jenkins_files/alfresco_restore_content_and_databse_only.JenkinsFile
> Updated docker tls path

- asg/main.tf
- asg/output.tf
- asg/variables.tf
- modules/asg/main.tf
- modules/asg/output.tf
- modules/asg/variables.tf
- user_data/user_data.sh
> Issue 140 refactor alfresco asg to aid release process

- README.md
- asg/main.tf
- asg/variables.tf
> Added new var and updated docs

- common/variables.tf
> Removed undefined vars

- efs/main.tf
- efs/variables.tf
> Updated EFS share

- asg/main.tf
- asg/variables.tf
- elk-migration/kibana.tf
- elk-migration/logstash.tf
- elk-migration/output.tf
- elk-migration/task_definitions/kibana.conf
- elk-migration/task_definitions/logstash.conf
- elk-migration/variables.tf
- jenkins_files/Alfresco_Terraform_Apply_Integrated_Environment.Jenkinsfile
- jenkins_files/alfresco_backup_full.JenkinsFile
- jenkins_files/check_infrastructure.Jenkinsfile
- modules/asg/main.tf
- modules/asg/variables.tf
- scripts/alfresco_database_backup.sh
- user_data/elasticsearch.sh
> Issue 152 elk migration fixes

- asg/main.tf
Fix the syntax of the conditional setting of the broker url
> Fix the syntax for the conditional setting of the message_broker_url

- asg/main.tf
- asg/variables.tf
- modules/asg/asg.tf
- modules/asg/variables.tf
- user_data/user_data.sh
> Added rolling updates to Alfresco ASG

- asg/main.tf
- asg/variables.tf
- modules/asg/asg.tf
- modules/asg/variables.tf
- user_data/user_data.sh
> Issue 174 rolling updates alfresco asg

- asg/main.tf
- asg/variables.tf
> added new ami_name var

- jenkins_files/alfresco_restore.JenkinsFile
- scripts/alfresco-database-restore.sh
- scripts/alfresco_database_backup.sh
- scripts/es5-restore.sh
- scripts/es6-restore.sh
> updated restore scripts

- Makefile
- pipelines/buildspec-alfresco-databases.yml
- pipelines/buildspec-alfresco-monitoring.yml
- pipelines/buildspec-alfresco-prereqs.yml
- pipelines/buildspec-alfresco-services.yml
- pipelines/buildspec-alfresco-storage.yml
Using ENV_CONFIGS_VERSION from pipeline
> Updated pipelines to use ENV_CONFIGS_VERSION var

- jenkins_files/Alfresco_Terraform_Apply_Integrated_Environment.Jenkinsfile
- jenkins_files/alfresco-release.Jenkinsfile
- jenkins_files/alfresco_backup_content_and_databse_only.JenkinsFile
- jenkins_files/alfresco_backup_full.JenkinsFile
- jenkins_files/alfresco_db_restore.Jenkinsfile
- jenkins_files/alfresco_release_pipeline.Jenkinsfile
- jenkins_files/check_infrastructure.Jenkinsfile
- jenkins_files/docker-run.Jenkinsfile
- jenkins_files/elasticsearch_migration.JenkinsFile
- jenkins_files/terraform_database.Jenkinsfile
- jenkins_files/terraform_deploy_test.Jenkinsfile
This change is allow Alfresco terraform builds to run in either codepipeline or jenkins
> Updated pipelines
